# iron/go:dev is the alpine image with the go tools added
FROM iron/go:dev

# add tools for debug and development purposes
RUN apk update && apk add vim && apk add iptables && apk add glide

ENV SRC_DIR=/gocode/src/github.com/containership/cloud-agent/

WORKDIR /app

# Add the source code:
ADD . $SRC_DIR

# Place login script in known location:
RUN mkdir -p /scripts && \
    cp $SRC_DIR/scripts/containership_login.sh /scripts

# Build it:
RUN cd $SRC_DIR && \
    glide install && \
    go build -o agent cmd/cloud_agent/agent.go && \
    cp agent /app/

ENTRYPOINT /app/agent
