FROM golang:1.8-alpine as builder

RUN apk add --no-cache git gcc musl-dev

# add tools for debug and development purposes
RUN apk update && \
    apk add vim && \
    apk add glide

ENV SRC_DIR=/go/src/github.com/containership/cloud-agent/

WORKDIR /app

# Add the source code:
ADD . $SRC_DIR

# Place login script in known location:
RUN mkdir -p /scripts && \
    cp $SRC_DIR/scripts/containership_login.sh /scripts

# Build it:
RUN cd $SRC_DIR && \
    glide install -v && \
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo -ldflags '-w' -o agent cmd/cloud_agent/agent.go && \
    cp agent /app/


# Create Docker image of just the binary
FROM scratch as runner
COPY --from=builder ./scripts /scripts
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder ./app/agent .
# TODO glog wants to log to a file by default. Don't use glog. See issue #36.
CMD ["./agent", "-logtostderr=true"]
