# This Dockerfile is only for CI tests
FROM golang:1.10.1-alpine3.7

# Add build tools
RUN apk update && \
    apk add --no-cache git gcc musl-dev curl

RUN curl -fsSL -o /usr/local/bin/dep https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 && \
    chmod +x /usr/local/bin/dep

ENV SRC_DIR=/go/src/github.com/containership/cloud-agent/

WORKDIR /app

# Install deps before adding rest of source so we can cache the resulting vendor dir
COPY Gopkg.toml Gopkg.lock $SRC_DIR
RUN cd $SRC_DIR && \
    dep ensure -vendor-only

# Add the source code:
COPY . $SRC_DIR

# These are only required for running Jenkins tests. This layer/dependency
# lives way down here because all previous layers are shared with prod builds.
RUN apk add --no-cache bash make

WORKDIR $SRC_DIR
