# This Dockerfile is only for Jenkins tests
FROM golang:1.10.1-alpine3.7

# Add build tools
RUN apk update && \
    apk add --no-cache git gcc musl-dev glide

ENV SRC_DIR=/go/src/github.com/containership/cloud-agent/

WORKDIR /app

# Glide install before adding rest of source so we can cache the resulting
# vendor dir
COPY glide.yaml glide.lock $SRC_DIR
RUN cd $SRC_DIR && \
        glide install -v

# Add the source code:
COPY . $SRC_DIR

# These are only required for running Jenkins tests. This layer/dependency
# lives way down here because all previous layers are shared with prod builds.
RUN apk add --no-cache bash make

WORKDIR $SRC_DIR
