# This dockerfile is only for Jenkins tests
FROM golang:1.10.1-alpine3.7

RUN apk update && \
    apk add --no-cache git gcc musl-dev && \
    apk add glide make

# add tools for debug and development purposes
RUN apk update && apk add glide && apk add bash

ENV SRC_DIR=/gocode/src/github.com/containership/cloud-agent/
ENV GOPATH=/gocode

WORKDIR /app

# Glide install before adding rest of source so we can cache the resulting
# vendor dir
ADD glide.yaml glide.lock $SRC_DIR
RUN cd $SRC_DIR && \
        glide install -v

# Add the source code:
ADD . $SRC_DIR

WORKDIR $SRC_DIR
