/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/containership/cluster-manager/pkg/apis/provision.containership.io/v3"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNodePoolLabels implements NodePoolLabelInterface
type FakeNodePoolLabels struct {
	Fake *FakeContainershipProvisionV3
	ns   string
}

var nodepoollabelsResource = schema.GroupVersionResource{Group: "provision.containership.io", Version: "v3", Resource: "nodepoollabels"}

var nodepoollabelsKind = schema.GroupVersionKind{Group: "provision.containership.io", Version: "v3", Kind: "NodePoolLabel"}

// Get takes name of the nodePoolLabel, and returns the corresponding nodePoolLabel object, and an error if there is any.
func (c *FakeNodePoolLabels) Get(name string, options v1.GetOptions) (result *v3.NodePoolLabel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(nodepoollabelsResource, c.ns, name), &v3.NodePoolLabel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v3.NodePoolLabel), err
}

// List takes label and field selectors, and returns the list of NodePoolLabels that match those selectors.
func (c *FakeNodePoolLabels) List(opts v1.ListOptions) (result *v3.NodePoolLabelList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(nodepoollabelsResource, nodepoollabelsKind, c.ns, opts), &v3.NodePoolLabelList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v3.NodePoolLabelList{ListMeta: obj.(*v3.NodePoolLabelList).ListMeta}
	for _, item := range obj.(*v3.NodePoolLabelList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nodePoolLabels.
func (c *FakeNodePoolLabels) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(nodepoollabelsResource, c.ns, opts))

}

// Create takes the representation of a nodePoolLabel and creates it.  Returns the server's representation of the nodePoolLabel, and an error, if there is any.
func (c *FakeNodePoolLabels) Create(nodePoolLabel *v3.NodePoolLabel) (result *v3.NodePoolLabel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(nodepoollabelsResource, c.ns, nodePoolLabel), &v3.NodePoolLabel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v3.NodePoolLabel), err
}

// Update takes the representation of a nodePoolLabel and updates it. Returns the server's representation of the nodePoolLabel, and an error, if there is any.
func (c *FakeNodePoolLabels) Update(nodePoolLabel *v3.NodePoolLabel) (result *v3.NodePoolLabel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(nodepoollabelsResource, c.ns, nodePoolLabel), &v3.NodePoolLabel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v3.NodePoolLabel), err
}

// Delete takes name of the nodePoolLabel and deletes it. Returns an error if one occurs.
func (c *FakeNodePoolLabels) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(nodepoollabelsResource, c.ns, name), &v3.NodePoolLabel{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNodePoolLabels) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(nodepoollabelsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v3.NodePoolLabelList{})
	return err
}

// Patch applies the patch and returns the patched nodePoolLabel.
func (c *FakeNodePoolLabels) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v3.NodePoolLabel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nodepoollabelsResource, c.ns, name, pt, data, subresources...), &v3.NodePoolLabel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v3.NodePoolLabel), err
}
