/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	"time"

	v3 "github.com/containership/cluster-manager/pkg/apis/containership.io/v3"
	scheme "github.com/containership/cluster-manager/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterLabelsGetter has a method to return a ClusterLabelInterface.
// A group's client should implement this interface.
type ClusterLabelsGetter interface {
	ClusterLabels(namespace string) ClusterLabelInterface
}

// ClusterLabelInterface has methods to work with ClusterLabel resources.
type ClusterLabelInterface interface {
	Create(*v3.ClusterLabel) (*v3.ClusterLabel, error)
	Update(*v3.ClusterLabel) (*v3.ClusterLabel, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v3.ClusterLabel, error)
	List(opts v1.ListOptions) (*v3.ClusterLabelList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v3.ClusterLabel, err error)
	ClusterLabelExpansion
}

// clusterLabels implements ClusterLabelInterface
type clusterLabels struct {
	client rest.Interface
	ns     string
}

// newClusterLabels returns a ClusterLabels
func newClusterLabels(c *ContainershipV3Client, namespace string) *clusterLabels {
	return &clusterLabels{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the clusterLabel, and returns the corresponding clusterLabel object, and an error if there is any.
func (c *clusterLabels) Get(name string, options v1.GetOptions) (result *v3.ClusterLabel, err error) {
	result = &v3.ClusterLabel{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clusterlabels").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterLabels that match those selectors.
func (c *clusterLabels) List(opts v1.ListOptions) (result *v3.ClusterLabelList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v3.ClusterLabelList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clusterlabels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterLabels.
func (c *clusterLabels) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("clusterlabels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a clusterLabel and creates it.  Returns the server's representation of the clusterLabel, and an error, if there is any.
func (c *clusterLabels) Create(clusterLabel *v3.ClusterLabel) (result *v3.ClusterLabel, err error) {
	result = &v3.ClusterLabel{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("clusterlabels").
		Body(clusterLabel).
		Do().
		Into(result)
	return
}

// Update takes the representation of a clusterLabel and updates it. Returns the server's representation of the clusterLabel, and an error, if there is any.
func (c *clusterLabels) Update(clusterLabel *v3.ClusterLabel) (result *v3.ClusterLabel, err error) {
	result = &v3.ClusterLabel{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clusterlabels").
		Name(clusterLabel.Name).
		Body(clusterLabel).
		Do().
		Into(result)
	return
}

// Delete takes name of the clusterLabel and deletes it. Returns an error if one occurs.
func (c *clusterLabels) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clusterlabels").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterLabels) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clusterlabels").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched clusterLabel.
func (c *clusterLabels) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v3.ClusterLabel, err error) {
	result = &v3.ClusterLabel{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("clusterlabels").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
