/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/containership/cluster-manager/pkg/apis/auth.containership.io/v3"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAuthorizationRoles implements AuthorizationRoleInterface
type FakeAuthorizationRoles struct {
	Fake *FakeContainershipAuthV3
	ns   string
}

var authorizationrolesResource = schema.GroupVersionResource{Group: "auth.containership.io", Version: "v3", Resource: "authorizationroles"}

var authorizationrolesKind = schema.GroupVersionKind{Group: "auth.containership.io", Version: "v3", Kind: "AuthorizationRole"}

// Get takes name of the authorizationRole, and returns the corresponding authorizationRole object, and an error if there is any.
func (c *FakeAuthorizationRoles) Get(name string, options v1.GetOptions) (result *v3.AuthorizationRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(authorizationrolesResource, c.ns, name), &v3.AuthorizationRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v3.AuthorizationRole), err
}

// List takes label and field selectors, and returns the list of AuthorizationRoles that match those selectors.
func (c *FakeAuthorizationRoles) List(opts v1.ListOptions) (result *v3.AuthorizationRoleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(authorizationrolesResource, authorizationrolesKind, c.ns, opts), &v3.AuthorizationRoleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v3.AuthorizationRoleList{ListMeta: obj.(*v3.AuthorizationRoleList).ListMeta}
	for _, item := range obj.(*v3.AuthorizationRoleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested authorizationRoles.
func (c *FakeAuthorizationRoles) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(authorizationrolesResource, c.ns, opts))

}

// Create takes the representation of a authorizationRole and creates it.  Returns the server's representation of the authorizationRole, and an error, if there is any.
func (c *FakeAuthorizationRoles) Create(authorizationRole *v3.AuthorizationRole) (result *v3.AuthorizationRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(authorizationrolesResource, c.ns, authorizationRole), &v3.AuthorizationRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v3.AuthorizationRole), err
}

// Update takes the representation of a authorizationRole and updates it. Returns the server's representation of the authorizationRole, and an error, if there is any.
func (c *FakeAuthorizationRoles) Update(authorizationRole *v3.AuthorizationRole) (result *v3.AuthorizationRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(authorizationrolesResource, c.ns, authorizationRole), &v3.AuthorizationRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v3.AuthorizationRole), err
}

// Delete takes name of the authorizationRole and deletes it. Returns an error if one occurs.
func (c *FakeAuthorizationRoles) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(authorizationrolesResource, c.ns, name), &v3.AuthorizationRole{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAuthorizationRoles) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(authorizationrolesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v3.AuthorizationRoleList{})
	return err
}

// Patch applies the patch and returns the patched authorizationRole.
func (c *FakeAuthorizationRoles) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v3.AuthorizationRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(authorizationrolesResource, c.ns, name, pt, data, subresources...), &v3.AuthorizationRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v3.AuthorizationRole), err
}
