/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/containership/cluster-manager/pkg/apis/containership.io/v3"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterLabels implements ClusterLabelInterface
type FakeClusterLabels struct {
	Fake *FakeContainershipV3
	ns   string
}

var clusterlabelsResource = schema.GroupVersionResource{Group: "containership.io", Version: "v3", Resource: "clusterlabels"}

var clusterlabelsKind = schema.GroupVersionKind{Group: "containership.io", Version: "v3", Kind: "ClusterLabel"}

// Get takes name of the clusterLabel, and returns the corresponding clusterLabel object, and an error if there is any.
func (c *FakeClusterLabels) Get(name string, options v1.GetOptions) (result *v3.ClusterLabel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(clusterlabelsResource, c.ns, name), &v3.ClusterLabel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v3.ClusterLabel), err
}

// List takes label and field selectors, and returns the list of ClusterLabels that match those selectors.
func (c *FakeClusterLabels) List(opts v1.ListOptions) (result *v3.ClusterLabelList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(clusterlabelsResource, clusterlabelsKind, c.ns, opts), &v3.ClusterLabelList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v3.ClusterLabelList{ListMeta: obj.(*v3.ClusterLabelList).ListMeta}
	for _, item := range obj.(*v3.ClusterLabelList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterLabels.
func (c *FakeClusterLabels) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(clusterlabelsResource, c.ns, opts))

}

// Create takes the representation of a clusterLabel and creates it.  Returns the server's representation of the clusterLabel, and an error, if there is any.
func (c *FakeClusterLabels) Create(clusterLabel *v3.ClusterLabel) (result *v3.ClusterLabel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(clusterlabelsResource, c.ns, clusterLabel), &v3.ClusterLabel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v3.ClusterLabel), err
}

// Update takes the representation of a clusterLabel and updates it. Returns the server's representation of the clusterLabel, and an error, if there is any.
func (c *FakeClusterLabels) Update(clusterLabel *v3.ClusterLabel) (result *v3.ClusterLabel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(clusterlabelsResource, c.ns, clusterLabel), &v3.ClusterLabel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v3.ClusterLabel), err
}

// Delete takes name of the clusterLabel and deletes it. Returns an error if one occurs.
func (c *FakeClusterLabels) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(clusterlabelsResource, c.ns, name), &v3.ClusterLabel{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterLabels) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(clusterlabelsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v3.ClusterLabelList{})
	return err
}

// Patch applies the patch and returns the patched clusterLabel.
func (c *FakeClusterLabels) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v3.ClusterLabel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(clusterlabelsResource, c.ns, name, pt, data, subresources...), &v3.ClusterLabel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v3.ClusterLabel), err
}
