/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	"time"

	v3 "github.com/containership/cluster-manager/pkg/apis/provision.containership.io/v3"
	scheme "github.com/containership/cluster-manager/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterUpgradesGetter has a method to return a ClusterUpgradeInterface.
// A group's client should implement this interface.
type ClusterUpgradesGetter interface {
	ClusterUpgrades(namespace string) ClusterUpgradeInterface
}

// ClusterUpgradeInterface has methods to work with ClusterUpgrade resources.
type ClusterUpgradeInterface interface {
	Create(*v3.ClusterUpgrade) (*v3.ClusterUpgrade, error)
	Update(*v3.ClusterUpgrade) (*v3.ClusterUpgrade, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v3.ClusterUpgrade, error)
	List(opts v1.ListOptions) (*v3.ClusterUpgradeList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v3.ClusterUpgrade, err error)
	ClusterUpgradeExpansion
}

// clusterUpgrades implements ClusterUpgradeInterface
type clusterUpgrades struct {
	client rest.Interface
	ns     string
}

// newClusterUpgrades returns a ClusterUpgrades
func newClusterUpgrades(c *ContainershipProvisionV3Client, namespace string) *clusterUpgrades {
	return &clusterUpgrades{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the clusterUpgrade, and returns the corresponding clusterUpgrade object, and an error if there is any.
func (c *clusterUpgrades) Get(name string, options v1.GetOptions) (result *v3.ClusterUpgrade, err error) {
	result = &v3.ClusterUpgrade{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clusterupgrades").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterUpgrades that match those selectors.
func (c *clusterUpgrades) List(opts v1.ListOptions) (result *v3.ClusterUpgradeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v3.ClusterUpgradeList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clusterupgrades").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterUpgrades.
func (c *clusterUpgrades) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("clusterupgrades").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a clusterUpgrade and creates it.  Returns the server's representation of the clusterUpgrade, and an error, if there is any.
func (c *clusterUpgrades) Create(clusterUpgrade *v3.ClusterUpgrade) (result *v3.ClusterUpgrade, err error) {
	result = &v3.ClusterUpgrade{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("clusterupgrades").
		Body(clusterUpgrade).
		Do().
		Into(result)
	return
}

// Update takes the representation of a clusterUpgrade and updates it. Returns the server's representation of the clusterUpgrade, and an error, if there is any.
func (c *clusterUpgrades) Update(clusterUpgrade *v3.ClusterUpgrade) (result *v3.ClusterUpgrade, err error) {
	result = &v3.ClusterUpgrade{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clusterupgrades").
		Name(clusterUpgrade.Name).
		Body(clusterUpgrade).
		Do().
		Into(result)
	return
}

// Delete takes name of the clusterUpgrade and deletes it. Returns an error if one occurs.
func (c *clusterUpgrades) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clusterupgrades").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterUpgrades) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clusterupgrades").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched clusterUpgrade.
func (c *clusterUpgrades) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v3.ClusterUpgrade, err error) {
	result = &v3.ClusterUpgrade{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("clusterupgrades").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
