/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	"time"

	v3 "github.com/containership/cluster-manager/pkg/apis/provision.containership.io/v3"
	scheme "github.com/containership/cluster-manager/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NodePoolLabelsGetter has a method to return a NodePoolLabelInterface.
// A group's client should implement this interface.
type NodePoolLabelsGetter interface {
	NodePoolLabels(namespace string) NodePoolLabelInterface
}

// NodePoolLabelInterface has methods to work with NodePoolLabel resources.
type NodePoolLabelInterface interface {
	Create(*v3.NodePoolLabel) (*v3.NodePoolLabel, error)
	Update(*v3.NodePoolLabel) (*v3.NodePoolLabel, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v3.NodePoolLabel, error)
	List(opts v1.ListOptions) (*v3.NodePoolLabelList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v3.NodePoolLabel, err error)
	NodePoolLabelExpansion
}

// nodePoolLabels implements NodePoolLabelInterface
type nodePoolLabels struct {
	client rest.Interface
	ns     string
}

// newNodePoolLabels returns a NodePoolLabels
func newNodePoolLabels(c *ContainershipProvisionV3Client, namespace string) *nodePoolLabels {
	return &nodePoolLabels{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the nodePoolLabel, and returns the corresponding nodePoolLabel object, and an error if there is any.
func (c *nodePoolLabels) Get(name string, options v1.GetOptions) (result *v3.NodePoolLabel, err error) {
	result = &v3.NodePoolLabel{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodepoollabels").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NodePoolLabels that match those selectors.
func (c *nodePoolLabels) List(opts v1.ListOptions) (result *v3.NodePoolLabelList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v3.NodePoolLabelList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodepoollabels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested nodePoolLabels.
func (c *nodePoolLabels) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("nodepoollabels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a nodePoolLabel and creates it.  Returns the server's representation of the nodePoolLabel, and an error, if there is any.
func (c *nodePoolLabels) Create(nodePoolLabel *v3.NodePoolLabel) (result *v3.NodePoolLabel, err error) {
	result = &v3.NodePoolLabel{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("nodepoollabels").
		Body(nodePoolLabel).
		Do().
		Into(result)
	return
}

// Update takes the representation of a nodePoolLabel and updates it. Returns the server's representation of the nodePoolLabel, and an error, if there is any.
func (c *nodePoolLabels) Update(nodePoolLabel *v3.NodePoolLabel) (result *v3.NodePoolLabel, err error) {
	result = &v3.NodePoolLabel{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nodepoollabels").
		Name(nodePoolLabel.Name).
		Body(nodePoolLabel).
		Do().
		Into(result)
	return
}

// Delete takes name of the nodePoolLabel and deletes it. Returns an error if one occurs.
func (c *nodePoolLabels) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nodepoollabels").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *nodePoolLabels) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nodepoollabels").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched nodePoolLabel.
func (c *nodePoolLabels) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v3.NodePoolLabel, err error) {
	result = &v3.NodePoolLabel{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("nodepoollabels").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
