/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	"time"

	v3 "github.com/containership/cluster-manager/pkg/apis/auth.containership.io/v3"
	scheme "github.com/containership/cluster-manager/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AuthorizationRolesGetter has a method to return a AuthorizationRoleInterface.
// A group's client should implement this interface.
type AuthorizationRolesGetter interface {
	AuthorizationRoles(namespace string) AuthorizationRoleInterface
}

// AuthorizationRoleInterface has methods to work with AuthorizationRole resources.
type AuthorizationRoleInterface interface {
	Create(*v3.AuthorizationRole) (*v3.AuthorizationRole, error)
	Update(*v3.AuthorizationRole) (*v3.AuthorizationRole, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v3.AuthorizationRole, error)
	List(opts v1.ListOptions) (*v3.AuthorizationRoleList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v3.AuthorizationRole, err error)
	AuthorizationRoleExpansion
}

// authorizationRoles implements AuthorizationRoleInterface
type authorizationRoles struct {
	client rest.Interface
	ns     string
}

// newAuthorizationRoles returns a AuthorizationRoles
func newAuthorizationRoles(c *ContainershipAuthV3Client, namespace string) *authorizationRoles {
	return &authorizationRoles{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the authorizationRole, and returns the corresponding authorizationRole object, and an error if there is any.
func (c *authorizationRoles) Get(name string, options v1.GetOptions) (result *v3.AuthorizationRole, err error) {
	result = &v3.AuthorizationRole{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("authorizationroles").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AuthorizationRoles that match those selectors.
func (c *authorizationRoles) List(opts v1.ListOptions) (result *v3.AuthorizationRoleList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v3.AuthorizationRoleList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("authorizationroles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested authorizationRoles.
func (c *authorizationRoles) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("authorizationroles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a authorizationRole and creates it.  Returns the server's representation of the authorizationRole, and an error, if there is any.
func (c *authorizationRoles) Create(authorizationRole *v3.AuthorizationRole) (result *v3.AuthorizationRole, err error) {
	result = &v3.AuthorizationRole{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("authorizationroles").
		Body(authorizationRole).
		Do().
		Into(result)
	return
}

// Update takes the representation of a authorizationRole and updates it. Returns the server's representation of the authorizationRole, and an error, if there is any.
func (c *authorizationRoles) Update(authorizationRole *v3.AuthorizationRole) (result *v3.AuthorizationRole, err error) {
	result = &v3.AuthorizationRole{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("authorizationroles").
		Name(authorizationRole.Name).
		Body(authorizationRole).
		Do().
		Into(result)
	return
}

// Delete takes name of the authorizationRole and deletes it. Returns an error if one occurs.
func (c *authorizationRoles) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("authorizationroles").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *authorizationRoles) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("authorizationroles").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched authorizationRole.
func (c *authorizationRoles) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v3.AuthorizationRole, err error) {
	result = &v3.AuthorizationRole{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("authorizationroles").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
