/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v3

import (
	time "time"

	provisioncontainershipiov3 "github.com/containership/cluster-manager/pkg/apis/provision.containership.io/v3"
	versioned "github.com/containership/cluster-manager/pkg/client/clientset/versioned"
	internalinterfaces "github.com/containership/cluster-manager/pkg/client/informers/externalversions/internalinterfaces"
	v3 "github.com/containership/cluster-manager/pkg/client/listers/provision.containership.io/v3"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterUpgradeInformer provides access to a shared informer and lister for
// ClusterUpgrades.
type ClusterUpgradeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v3.ClusterUpgradeLister
}

type clusterUpgradeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewClusterUpgradeInformer constructs a new informer for ClusterUpgrade type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterUpgradeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClusterUpgradeInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredClusterUpgradeInformer constructs a new informer for ClusterUpgrade type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClusterUpgradeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ContainershipProvisionV3().ClusterUpgrades(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ContainershipProvisionV3().ClusterUpgrades(namespace).Watch(options)
			},
		},
		&provisioncontainershipiov3.ClusterUpgrade{},
		resyncPeriod,
		indexers,
	)
}

func (f *clusterUpgradeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClusterUpgradeInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clusterUpgradeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&provisioncontainershipiov3.ClusterUpgrade{}, f.defaultInformer)
}

func (f *clusterUpgradeInformer) Lister() v3.ClusterUpgradeLister {
	return v3.NewClusterUpgradeLister(f.Informer().GetIndexer())
}
