#!/bin/bash

SCRIPT_NAME=$(basename $0)

SRC_DIR=$GOPATH/src/github.com/containership/cloud-agent
cd $SRC_DIR

#vendor/k8s.io/code-generator/generate-groups.sh all \
  #github.com/containership/cloud-agent/pkg/client github.com/containership/cloud-agent/pkg/apis \
  #containership.io:v3

# TODO see https://github.com/kubernetes/code-generator/issues/30. This is
# needed in addition to the Makefile lint workaround because we want to lint
# the pkg directory but we can't explicitly ignore individual files. Also note
# that BSD/macOS sed is weird and requires an actual newline - \n does not work
find pkg -type f -name 'zz_generated.*' -exec \
  sed -i '' "1s|^|// Code generated by $SCRIPT_NAME. DO NOT EDIT.\\
|" {} \;
